### ISSUE TITLE
Catch the `ENOENT` error after One-Click Import

### ISSUE THREAD

**Issue by jaaufauvre** [Mastercard/insomnia-plugin-mastercard-auth#11]
After the Mastercard APIs workspace was imported (see [One-Click Import](https://github.com/Mastercard/insomnia-plugin-mastercard-auth#one-click-import)), a `ENOENT` error can occur if the user doesn't update the default plugin configuration before sending a request:

![image](https://user-images.githubusercontent.com/3964455/68467515-3e862d80-020e-11ea-9e50-ebc2b8b73562.png)

Default configuration:
```
{
  "host": "https://sandbox.api.mastercard.com",
  "mastercard": {
    "consumerKey": "000000000000000000000000000000000000000000000000!000000000000000000000000000000000000000000000000",
    "keyAlias": "keyalias",
    "keystoreP12Path": "/path/to/sandbox-signing-key.p12",
    "keystorePassword": "keystorepassword"
  }
}
```

In that case (`consumerKey` being `0000...0000` or `keystoreP12Path` containing `/path/to/`), the plugin could display a proper alert. 

For instance: "_Default configuration detected! Don't forget to update your Mastercard credentials in the 'Manage Environments' section._".

The user could also be prompted for the different elements of configuration in case those are wrong or missing.

**Comment by ivyxiao123** [comment]
Hi,
I updated the consumerKey and path to the right one but still getting this ENOENT error saying no such file, any idea?

**Comment by sjransom** [comment]
Also having the same issue as @ivyxiao123 - although it's not clear what the `/path/to/` should be on OSX? Can you give an example? Thanks

**Comment by DonalRafferty** [comment]
@ivyxiao123, @ivyxiao123 for Mac right click on the file in 'Finder', then hold down the alt/options key and in the drop down menu you will see the option ti 'Copy "name of your file" as PathName'. This is the value you supply.

It will be something like this:

/Users/yourusername/development/spring/gs-spring-boot/initial/src/config/keys/sandbox.p12

**Comment by sjransom** [comment]
@DonalRafferty got it, thanks!

**Comment by ivyxiao123** [comment]
@DonalRafferty fixed, thanks!

**Comment by rossphelan** [comment]
The error messages have now been updated to avoid confusion in the future.
