### ISSUE TITLE
Unknown Error Open

### ISSUE THREAD

**Issue by magaras** [Mastercard/insomnia-plugin-mastercard-auth#14]
Good day everyone,

Trying to use the plugin i get the following error : 

![image](https://user-images.githubusercontent.com/5760786/81951271-a0847d00-960d-11ea-9461-d37b64d1e7a0.png)

I set up the environment by providing all the values.

Am I missing a step here?

Info :  I use Windows 10 and "Insomnia 7.1.1"

Thanks,

**Comment by magaras** [comment]
the path is not supposed to be that way.

C://xxx/xxx.p12

**Comment by jaaufauvre** [comment]
Hi @magaras, I see you closed this issue.
Yes, a regular Windows file path should work:
```json
{
  "host": "https://sandbox.api.mastercard.com",
  "mastercard": {
    "consumerKey": "000000000000000000000000000000000000000000000000!000000000000000000000000000000000000000000000000",
    "keyAlias": "keyalias",
    "keystoreP12Path": "C:/path/to/sandbox-signing-key.p12",
    "keystorePassword": "keystorepassword"
  }
}
```
