### ISSUE TITLE
The URI does not contain a valid specification Error

### ISSUE THREAD

**Issue by gbandeira81** [Mastercard/insomnia-plugin-mastercard-auth#16]
With the latest windows version of Insomnia (2020.3.3) .When trying to follow the steps on the readme.md, during the Configuration step, the following error is being thrown:

Error: No importers found for file
    at module.exports.convert (~\AppData\Local\insomnia\app-2020.3.3\resources\app.asar\node_modules\insomnia-importers\index.js:44:9)

**Comment by danny-gallagher** [comment]
@gbandeira81 Thank you for reporting this issue! There was an issue regarding the JSON workspace URI used in the README. This should be resolved now with the latest release.

**Comment by e109772** [comment]
When trying to follow the steps on the readme.md, during the Configuration step, i am getting no import file found.

**Comment by danny-gallagher** [comment]
Hey @e109772 
Thanks for your comment. We are having trouble reproducing the issue you've reported.
Can you provide us with some more information on replicating this issue?

- What OS/browser are you using?
- We describe 2 methods of importing the workspace into insomnia in the 'Configuration' section. Which of the 2 are giving you the error?
