### ISSUE TITLE
Non-compliant handling of non standard port numbers in URI

### ISSUE THREAD

**Issue by mastercard-rob** [Mastercard/insomnia-plugin-mastercard-auth#6]
v1.0.5

I was testing against a local service that implements OAuth1.0a and discovered the following issue.

The following is the Signature Base String calculated by the plugin for a GET request to http://localhost:8080/test

GET&http%3A%2F%2Flocalhost&oauth_body_hash%3D47DEQpj8HBSa%252B%252FTImW%252B5JCeuQeRkm5NMpJWZG3hSuFU%253D%26oauth_consumer_key%3D-yKelzvPcUkWb8M6Rqa27h23x-7WbjxZUqSR4FYWa34ac848%2521606c3c6395e7469a98cb3351f82f98860000000000000000%26oauth_nonce%3DikFV505E%26oauth_signature_method%3DRSA-SHA256%26oauth_timestamp%3D1565713741%26oauth_version%3D1.0

The following is the value I would expect with the non-standard port number and path remaining in tact
GET&http%3A%2F%2Flocalhost%3A8080%2Ftest&oauth_body_hash%3D47DEQpj8HBSa%252B%252FTImW%252B5JCeuQeRkm5NMpJWZG3hSuFU%253D%26oauth_consumer_key%3D-yKelzvPcUkWb8M6Rqa27h23x-7WbjxZUqSR4FYWa34ac848%2521606c3c6395e7469a98cb3351f82f98860000000000000000%26oauth_nonce%3DikFV505E%26oauth_signature_method%3DRSA-SHA256%26oauth_timestamp%3D1565713741%26oauth_version%3D1.0

**Comment by kkrauth** [comment]
@kenny-chow-my suggest updating this plugin to utilize the official OAuth1 library:
https://github.com/Mastercard/oauth1-signer-nodejs
that has proper non-standard port handling (https://github.com/Mastercard/oauth1-signer-nodejs/blob/master/src/OAuth.js#L111) and other improvements over this implementation.

**Comment by piyuhirpara** [comment]
Resolved in version 1.1.0
